services:

# Defining Mongo DB container
  mongo:
    image: mongo:7
    container_name: wanderlust-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - wanderlust-net

# Defining Ollama container
  ollama:
    image: ollama/ollama:latest
    container_name: wanderlust-ollama
    restart: unless-stopped
      #    ports:
      # - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD-SHELL", "ollama list || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 13
      start_period: 40s
    networks:
      - wanderlust-net  
# One time job -Pull tinyllama model
  ollama-pull:
    image: ollama/ollama:latest
    container_name: wanderlust-ollama-pull
    depends_on:
      ollama:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        ollama pull tinyllama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    networks:
      - wanderlust-net
    restart: "no"


# Defining WanderlustAI interegated APP container
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: wanderlust-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
    # as Define in the READEME and .envfile
    # override DB url to use mongo container
      ATLASDB_URL: mongodb://mongo:27017/wanderlust
    # point to ollama container
      OLLAMA_URL: http://ollama:11434
    depends_on:
      mongo:
        condition: service_healthy
      ollama:
        condition: service_healthy
      ollama-pull:
        condition: service_completed_successfully
    networks:
      - wanderlust-net   

# Defining networks
networks:
  wanderlust-net:
    driver: bridge

# Defining volumes
volumes:
  ollama_data:
  mongo_data:
